export const GAPI_CONFIG = {
  CLIENT_ID: process.env.NEXT_PUBLIC_GAPI_CLIENT_ID,
  SCOPES: process.env.NEXT_PUBLIC_GAPI_SCOPES,
  API_KEY: process.env.NEXT_PUBLIC_GAPI_API_KEY,
  DISCOVERY_DOC: process.env.NEXT_PUBLIC_GAPI_DISCOVERY_DOC
};
